"""Changes models

Revision ID: 8f10a7f8cdca
Revises: 66edb8eb6eb2
Create Date: 2023-10-29 16:14:55.766212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f10a7f8cdca'
down_revision = '66edb8eb6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
